CREATE TABLE IF NOT EXISTS mentorship_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mentorshipId INT NOT NULL,
  mentorId INT NOT NULL,
  menteeId INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  scheduledAt DATETIME NOT NULL,
  duration INT DEFAULT 60,
  status ENUM('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show') DEFAULT 'scheduled',
  meetingLink VARCHAR(255),
  meetingType ENUM('video', 'audio', 'in_person') DEFAULT 'video',
  notes TEXT,
  mentorNotes TEXT,
  menteeNotes TEXT,
  rating INT,
  feedback TEXT,
  completedAt DATETIME,
  cancelledAt DATETIME,
  cancellationReason TEXT,
  reminderSent BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (mentorshipId) REFERENCES mentorship_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (mentorId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (menteeId) REFERENCES users(id) ON DELETE CASCADE
);
